# Generated by Microsoft365DSC from https://export.microsoft365dsc.com on 23/04/2024 11:36:16
# Visit https://microsoft365dsc.com for more information

# Getting client credential
$Credential = Get-Credential

# Exporting resources using credentials
Export-M365DSCConfiguration -Components @("AADGroupsSettings") -Credential $Credential -Path "C:\Users\tbouchet\Downloads\Test\group"
